"""empty message

Revision ID: b5b613e1a1b7
Revises: None
Create Date: 2016-06-12 18:40:38.407141

"""

# revision identifiers, used by Alembic.
revision = 'b5b613e1a1b7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bros_email'), 'bros', ['email'], unique=True)
    op.create_index(op.f('ix_bros_username'), 'bros', ['username'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bros_username'), table_name='bros')
    op.drop_index(op.f('ix_bros_email'), table_name='bros')
    op.drop_table('bros')
    ### end Alembic commands ###
