"""empty message

Revision ID: 8b2ff0814292
Revises: eb8c8c227e6e
Create Date: 2016-06-15 03:33:38.971684

"""

# revision identifiers, used by Alembic.
revision = '8b2ff0814292'
down_revision = 'eb8c8c227e6e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bros', sa.Column('best_friend_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bros', 'bros', ['best_friend_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bros', type_='foreignkey')
    op.drop_column('bros', 'best_friend_id')
    ### end Alembic commands ###
