"""empty message

Revision ID: df10efff3fe0
Revises: 8b2ff0814292
Create Date: 2016-06-28 12:53:08.306679

"""

# revision identifiers, used by Alembic.
revision = 'df10efff3fe0'
down_revision = '8b2ff0814292'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'friendships_bro_id_fkey', 'friendships', type_='foreignkey')
    op.drop_constraint(u'friendships_friend_id_fkey', 'friendships', type_='foreignkey')
    op.create_foreign_key(None, 'friendships', 'bros', ['friend_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'friendships', 'bros', ['bro_id'], ['id'], ondelete='cascade')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'friendships', type_='foreignkey')
    op.drop_constraint(None, 'friendships', type_='foreignkey')
    op.create_foreign_key(u'friendships_friend_id_fkey', 'friendships', 'bros', ['friend_id'], ['id'])
    op.create_foreign_key(u'friendships_bro_id_fkey', 'friendships', 'bros', ['bro_id'], ['id'])
    ### end Alembic commands ###
