"""empty message

Revision ID: eb8c8c227e6e
Revises: b5b613e1a1b7
Create Date: 2016-06-14 01:24:20.252886

"""

# revision identifiers, used by Alembic.
revision = 'eb8c8c227e6e'
down_revision = 'b5b613e1a1b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('bro_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bro_id'], ['bros.id'], ),
    sa.ForeignKeyConstraint(['friend_id'], ['bros.id'], ),
    sa.UniqueConstraint('bro_id', 'friend_id', name='unique_friendships')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendships')
    ### end Alembic commands ###
